version: '2'

services:
  influxdb:
    image: influxdb:1.3.6
    ports:
      - "8083:8083"
      - "8086:8086"
    volumes:
      - ./influx:/var/lib/influxdb
      #- ./influx-config.conf:/etc/influxdb/influxdb.conf
  grafana:
    image: grafana/grafana:4.5.2
    ports:
      - "3000:3000"
    volumes:
      - ./grafana:/var/lib/grafana