version: "2.1"
services:
  producer:
    image: bigdata/event-producer:latest
    networks:
      - default
      - cluster_default
    ports:
      - "8080:8080"
  consumer:
    image: bigdata/event-consumer:latest
    networks:
      - default
      - cluster_default
networks:
  cluster_default:
    external: true